### ISSUE TITLE
Bug na imagem pós acerto/erro e dica de funcionalidade

### ISSUE THREAD

**Issue by matheusfelipeog** [lluukinha/whos-that-pokemon#1]
Olá, @lluukinha 😄

Muito bacana o projeto, show de bola.

## Bug

Quando seleciono o Pokemon correto ou errado, após clicar em next/reset a sombra do que acabei de selecionar aparece brevemente, como na demonstração abaixo:

![Demonstração](https://user-images.githubusercontent.com/50463866/90432566-1979f180-e0a1-11ea-9876-96ea26da281d.gif)

## Dica

E também deixo uma dica de funcionalidade, cujo não encontrei o motivo para não existir: Sempre que acertar, invés de ter que clicar no next, já o faça passar para o próximo pokemon automaticamente. Que tal?

**Comment by lluukinha** [comment]
Obrigado pelo seu comentário amigo, fiz algumas mudanças baseadas no que me passou.
Realmente atualizar automaticamente fica mais legal do que clicar em next.

Sobre o bug, é de acordo com a velocidade que é baixada a proxima imagem, o que fiz foi usar uma imagem intermediária. (o problema era que se eu trocasse a imagem repentinamente, poderia aparecer a imagem do proximo pokemon antes de dar fade).

Valeu mesmo!
